/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.AvailDesk.Activity;

import com.AvailDesk.Controller.IssueController;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.net.URL;
import java.net.URLConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.net.www.http.HttpClient;

/**
 *
 * @author ROG STRIX
 */
public class AssignEmployeeActivity extends javax.swing.JFrame {

    /**
     * Creates new form AssignEmployeeActivity
     */
     String id  = null;
        IssueController IssueController = new IssueController();
     public AssignEmployeeActivity() {
        initComponents();
          setBackground(new Color(0, 0, 0, 0));
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/availdesk/images/mainlogo.png")));
      loadEmployee();
    }
     public AssignEmployeeActivity(String data) {
        initComponents();
         setBackground(new Color(0, 0, 0, 0));
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/availdesk/images/mainlogo.png")));
   
        id = data;
     
       loadEmployee();
        
    }
 public void loadEmployee()
     {
         
         Connection con;
         String URL = "jdbc:mysql://localhost:3306/availdesk?zeroDateTimeBehavior=CONVERT_TO_NULL";
         String Uname = "root";
         String Password = "";
         try
        {
             con = DriverManager.getConnection(URL,Uname,Password);
             String query = "SELECT * FROM `users` ORDER BY id ASC";
             Statement stm = con.createStatement();
             ResultSet rs = stm.executeQuery(query);
         
              
      
             while(rs.next())
             {
                 String id = rs.getString("id");
                 String type = rs.getString("type");
                 if(!type.equals("admin")){
                     
                 
                 String username = rs.getString("username");
                 String password = rs.getString("password");
                 String email = rs.getString("email");
                 String tbData[] = {id,username,email}; 
                 DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
                                
                 tblmodel.addRow(tbData);
                 }
             }
             
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex, "Success!", JOptionPane.INFORMATION_MESSAGE);
        }
     }
    public void sendEmail(String email,String name,String body)
    {
        try
        {
    String sURL = "https://2hostout.com/email/api/v1/payeen/test4availdesk.php?email="+email+"&name="+name+"&body="+body+""; 

   
    URL url = new URL(sURL);
    URLConnection request = url.openConnection();
    request.connect();
     //JOptionPane.showMessageDialog(null,  request.getContent(), "Success!", JOptionPane.INFORMATION_MESSAGE);
   System.out.println(request.getContent());
     }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex, "Success!", JOptionPane.INFORMATION_MESSAGE);
        }
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<< GO BACK");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 340, 86, 17);

        jLabel4.setBackground(new java.awt.Color(226, 239, 248));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(221, 237, 242));
        jLabel4.setText("Avail Desk");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 340, 62, 15);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "EmployeeName", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 80, 340, 190);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ASSIGN");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 280, 150, 30);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 33)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Assign Employee");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 30, 290, 39);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("x");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 10, 19, 43);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/AvailDesk/Images/bg1.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 410, 370);

        setSize(new java.awt.Dimension(409, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new IssueManageActivity().setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jTable1.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "Select any employee to assign!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
            String eid = tblmodel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        if(IssueController.assignEmployee(eid,id))
        {
            sendEmail(tblmodel.getValueAt(jTable1.getSelectedRow(), 2).toString(),tblmodel.getValueAt(jTable1.getSelectedRow(), 1).toString(),"You+have+a+new+issue+to+solve!+Please+login+to+resolve!");
        JOptionPane.showMessageDialog(null, "Successfully Employee Assigned!", "Success!", JOptionPane.INFORMATION_MESSAGE);
          new IssueManageActivity().setVisible(true);
        setVisible(false);
        
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid username or password!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
  

        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignEmployeeActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignEmployeeActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignEmployeeActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignEmployeeActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignEmployeeActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
